name: Test Workflow

on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  test-configuration:
    name: Test Configuration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Test Maven configuration
      run: |
        echo "Testing Maven configuration..."
        mvn help:effective-pom | grep -A 5 -B 5 "versions-maven-plugin"
        mvn help:effective-pom | grep -A 5 -B 5 "maven-gpg-plugin"
        mvn help:effective-pom | grep -A 5 -B 5 "central-publishing-maven-plugin"
        
    - name: Test version extraction
      run: |
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Current version: $CURRENT_VERSION"
        
    - name: Test build (without signing)
      run: |
        mvn clean compile test-compile
        
    - name: Check workflow files
      run: |
        echo "GitHub Actions workflow files:"
        ls -la .github/workflows/
        echo ""
        echo "Setup documentation:"
        ls -la GITHUB_ACTIONS_SETUP.md
        echo ""
        echo "GPG export script:"
        ls -la export-gpg-key.sh
